CHP/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from CHP.views import *
from CHP.authFunctions import *

authFunctionsList = [
    path('signup',user_signup),
    path('signin',user_login,name='signin'),
    path('signout',user_logout),
    path('changepass',change_password, name='change_password'),
    path('changeprof',change_profile, name='change_profile'),
    path('activate/<uidb64>[0-9A-Za-z_\-]+/<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20}',user_activation, name='activate'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='partials/password_reset/form.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='partials/password_reset/done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='partials/password_reset/confirm.html'),name='password_reset_confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='partials/password_reset/complete.html'),name='password_reset_complete')
]

adminFunctionsList=[
    path('dashboard',dashboard),
    path('manage-categories',manage_categories,name='manage-categories'),
    path('manage-data',manage_data,name='manage-data'),
    path('manage-users',manage_users,name='manage-users'),
    path('manage/<str:category>',manage_data_cat,),
    path('add/<str:name>',add,name='add'),
    path('addData/<str:category>',add_data,name='addData'),
    path('edit/<str:name>/<int:id>',edit,name='edit'),
    path('editData/<str:category>/<int:id>',edit_data,name='editData'),
    path('delete/<str:name>/<int:id>',delete,name='delete'),
    path('deleteData/<str:category>/<int:id>',delete_data,name='deleteData'),
]

genericUrls = [
    path('',home),
    path('breifpage/<str:category>',breifPage),
    path('detailpage/<str:category>/<int:id>',detailPage),
]
urlpatterns=authFunctionsList+genericUrls+adminFunctionsList

ICHG/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CHP.urls'))
]

CHP/models.py
from ICHG.settings import STATE_LIST
from django.db import models
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin,Group
from django.utils.translation import ugettext_lazy as _
from cloudinary.models import CloudinaryField


class UserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must have is_staff=True.'
            )
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must have is_superuser=True.'
            )

        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True,max_length=255,blank=False)
    first_name = models.CharField(_('first name'),max_length=150,blank=True)
    last_name = models.CharField(_('last name'),max_length=150,blank=True)
    is_staff = models.BooleanField(_('staff status'),default=False)
    is_active = models.BooleanField(_('active'),default=False)
    is_superuser = models.BooleanField(_('superuser'),default=False)
    date_joined = models.DateTimeField(_('date joined'),default=timezone.now)
    usergroup = models.ForeignKey(Group,related_name="groups",on_delete=models.SET_NULL,null=True)
  
    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.email

    def full_name(self):
        return self.first_name+" "+self.last_name

class Categories(models.Model):
    name = models.TextField()
    icon = CloudinaryField(overwrite=True,)
    # input fields for category
    field1 = models.TextField(null=True,blank=True)
    field2 = models.TextField(null=True,blank=True)
    field3 = models.TextField(null=True,blank=True)
    field4 = models.TextField(null=True,blank=True)
    field5 = models.TextField(null=True,blank=True)
    field6 = models.TextField(null=True,blank=True)
    field7 = models.TextField(null=True,blank=True)
    field8 = models.TextField(null=True,blank=True)
    field9 = models.TextField(null=True,blank=True)
    field10 = models.TextField(null=True,blank=True)
    field11 = models.TextField(null=True,blank=True)
    field12 = models.TextField(null=True,blank=True)
    field13 = models.TextField(null=True,blank=True)
    field14 = models.TextField(null=True,blank=True)
    field15 = models.TextField(null=True,blank=True)
    field16 = models.TextField(null=True,blank=True)
    field17 = models.TextField(null=True,blank=True)
    field18 = models.TextField(null=True,blank=True)
    field19 = models.TextField(null=True,blank=True)
    field20 = models.TextField(null=True,blank=True)
    is_shown = models.BooleanField(default=True)
    class Meta: 
        verbose_name = "Category"
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return self.name

class AllData(models.Model):
    category = models.ForeignKey(Categories,related_name="category",on_delete=models.SET_NULL,null=True)
    name = models.TextField(null=True,blank=True)
    phone1 = models.TextField(null=True,blank=True)
    phone2 = models.TextField(null=True,blank=True)
    phone3 = models.TextField(null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    website = models.URLField(null=True,blank=True)
    address = models.TextField(null=True,blank=True)
    landmark = models.TextField(null=True,blank=True)
    pincode = models.IntegerField(null=True,blank=True)
    city = models.TextField(null=True,blank=True)
    state = models.CharField(
        max_length=30,
        choices=STATE_LIST,
        default='DL'
    )
    mapUrl = models.URLField(null=True,blank=True)
    field1 = models.TextField(null=True,blank=True)
    field2 = models.TextField(null=True,blank=True)
    field3 = models.TextField(null=True,blank=True)
    field4 = models.TextField(null=True,blank=True)
    field5 = models.TextField(null=True,blank=True)
    field6 = models.TextField(null=True,blank=True)
    field7 = models.TextField(null=True,blank=True)
    field8 = models.TextField(null=True,blank=True)
    field9 = models.TextField(null=True,blank=True)
    field10 = models.TextField(null=True,blank=True)
    field11 = models.TextField(null=True,blank=True)
    field12 = models.TextField(null=True,blank=True)
    field13 = models.TextField(null=True,blank=True)
    field14 = models.TextField(null=True,blank=True)
    field15 = models.TextField(null=True,blank=True)
    field16 = models.TextField(null=True,blank=True)
    field17 = models.TextField(null=True,blank=True)
    field18 = models.TextField(null=True,blank=True)
    field19 = models.TextField(null=True,blank=True)
    field20 = models.TextField(null=True,blank=True)
    is_verified = models.BooleanField(default=False)
    is_shown = models.BooleanField(default=False)

CHP/views.py
from CHP.models import *
from CHP.forms import *
from cloudinary.forms import cl_init_js_callbacks
from django.contrib.auth import *
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from django.contrib import messages
from django.http import JsonResponse
from django.http.request import QueryDict,MultiValueDict
from django.forms.models import model_to_dict

def home(request):
    return render(request,'home.html',{'categories':Categories.objects.all()})

def breifPage(request,category):
    allData = AllData.objects.filter(category=Categories.objects.get(name=category))
    return render(request,'breifPage.html',{'allData':allData})

def detailPage(request,category,id):
    data = AllData.objects.filter(id=id)[0]
    return render(request,'detailPage.html',{'data':data})

def dashboard(request):
    if request.user.is_authenticated:
        if set(['Verifier','Admin','Editor']).intersection(set(str(i) for i in request.user.groups.all()))!=set():
            return render(request,'admin/dashboard.html',{'user':request.user})
        else:
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/signin')

def manage_users(request):
    if request.user.has_perm('CHP.view_user'):
        allusers = User.objects.all()
        return render(request,'admin/manage.html',{'name':'Users','users':allusers})
    else:
        return HttpResponseRedirect('/signin')

def manage_categories(request):
    if request.user.has_perm('CHP.view_categories'):
        categories = Categories.objects.all()
        return render(request,'admin/manage.html',{'name':'Categories','categories':categories})
    else:
        return HttpResponseRedirect('/signin')

def manage_data(request):
    if request.user.has_perm('CHP.view_alldata'):
        return render(request,'admin/manage_data.html',{'alldata':AllData.objects.all(),'categories':Categories.objects.all()})
    else:
        return HttpResponseRedirect('/signin')

def manage_data_cat(request,category):
    alldata = AllData.objects.filter(category=Categories.objects.get(name=category).id)
    return render(request,'admin/manage.html',{
            'name':f"{category} Data",'alldata':alldata,
            'category':Categories.objects.get(name=category)
        })

def add(request,name):
    if request.user.has_perm('CHP.add_'+name):
        if request.method == 'POST':
            if name == 'categories':
                form = AddCategoryForm(request.POST,request.FILES)
                if form.is_valid():
                    form.save()
                    messages.success(request,'Successfully added Category')
                    return HttpResponseRedirect('/manage-categories')
            elif name == 'user':
                form = SignUpForm(request.POST)
                if form.is_valid():
                    form.save()
                    messages.success(request,'Successfully added User')
                    return HttpResponseRedirect('/manage-users')
        else:
            if name == 'categories':
                sname="Category"
                form = AddCategoryForm()
            elif name == 'user':
                sname="User"
                form = SignUpForm()
            else:
                return HttpResponseRedirect('/dashboard')
            return render(request,'admin/add_edit.html',{'name':f'Add {sname}','form':form})
    else:
        return HttpResponseRedirect('/signin')


def add_data(request,category):
    if request.user.has_perm('CHP.add_alldata'):
        if request.method == 'POST':
            form = AddDataForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request,'Successfully added Data')
                return HttpResponseRedirect(f'/manage/{category}')
        else:
            dataField = {}
            for k,v in model_to_dict(Categories.objects.get(name=category)).items():
                if k not in ['','id','icon'] and v!='':
                    dataField[k]=v
            form = AddDataForm()
            dataField['name'],dataField['phone1'],dataField['phone2'],dataField['phone3']="Name","Phone Number","2nd Phone Number","3rd Phone Number",
            dataField['email'],dataField['address1'],dataField['pincode'],dataField['city']="Email","Address","Pincode","City",
            dataField['state'],dataField['website'],dataField['mapUrl']="","Website","Map Location Link"
            return render(request,'admin/add_edit.html',{
                                        'name':f'Add Data','form':form,
                                        'dataField':dataField,'categoryId':Categories.objects.get(name=category).id,
                                        'categoryName':category
                                    }
                        )
    else:
        return HttpResponseRedirect('/signin')


def edit(request,name,id):
    if request.user.has_perm('CHP.change_'+name):
        if request.method == 'POST':
            if name == 'categories':
                data = Categories.objects.get(pk=id)
                form = AddCategoryForm(request.POST,request.FILES,instance=data)
                if form.is_valid():
                    form.save()
                    messages.success(request,'Successfully Changed Category')
                    return HttpResponseRedirect('/manage-categories')
            elif name == 'user':
                data = User.objects.get(pk=id)
                form = AdminUserChangeForm(request.POST,instance=data)
                if form.is_valid():
                    data.groups.clear()
                    data.groups.add(form.cleaned_data['usergroup'])
                    form.save()
                    messages.success(request,'Successfully Changed User')
                    return HttpResponseRedirect('/manage-users')
        else:
            if name == 'categories':
                sname="Category"
                data = Categories.objects.get(pk=id)
                form = AddCategoryForm(instance=data)
            elif name == 'user':
                sname="User"
                data = User.objects.get(pk=id)
                form = AdminUserChangeForm(instance=data)
            else:
                return HttpResponseRedirect('/dashboard')
            return render(request,'admin/add_edit.html',{'name':f'Edit {sname}','form':form,'everyDetail':data})
    else:
        return HttpResponseRedirect('/signin')


def edit_data(request,category,id):
    if request.user.has_perm('CHP.add_alldata'):
        if request.method == 'POST':
            data = AllData.objects.get(pk=id)
            form = AddDataForm(request.POST,instance=data)
            if form.is_valid():
                form.save()
                messages.success(request,'Successfully Changed Data')
                return HttpResponseRedirect(f'/manage/{category}')
        else:
            dataField = {}
            for k,v in model_to_dict(Categories.objects.get(name=category)).items():
                if k not in ['','id','name','icon'] and v!='':
                    dataField[k]=v
            data = AllData.objects.get(pk=id)
            form = AddDataForm(instance=data)
            dataField['name'],dataField['phone1'],dataField['phone2'],dataField['phone3']="Name","Phone Number","2nd Phone Number","3rd Phone Number",
            dataField['email'],dataField['address'],dataField['landmark'],dataField['pincode'],dataField['city']="Email","Address","Landmark","Pincode","City",
            dataField['state'],dataField['website'],dataField['mapUrl']="","Website","Map Location Link"
            return render(request,'admin/add_edit.html',{
                                        'name':f'Edit Data','form':form,
                                        'dataField':dataField,'categoryId':Categories.objects.get(name=category).id,
                                        'categoryName':category,'id':id
                                    }
                        )
    else:
        return HttpResponseRedirect('/signin')

def delete(request,name,id):
    if request.user.has_perm('CHP.delete_'+name):
        if request.method == 'POST':
            if name == 'categories':
                category = Categories.objects.get(pk=id)
                category.delete()
                messages.success(request,'Successfully Deleted Category')
                return HttpResponseRedirect('/manage-categories')
            elif name == 'user':
                user = User.objects.get(pk=id)
                user.delete()
                messages.success(request,'Successfully Deleted User')
                return HttpResponseRedirect('/manage-users')
        else:
            if name == 'categories':
                messages.success(request,'Category Deletion Unsuccessful')
                return HttpResponseRedirect('/manage-categories')
            elif name == 'user':
                messages.success(request,'User Deletion Unsuccessful')
                return HttpResponseRedirect('/manage-users')
            else:
                return HttpResponseRedirect('/dashboard')
    else:
        return HttpResponseRedirect('/signin')

def delete_data(request,category,id):
    if request.user.has_perm('CHP.delete_alldata'):
        if request.method == 'POST':
            data = AllData.objects.get(pk=id)
            data.delete()
            messages.success(request,'Successfully Deleted Data')
            return HttpResponseRedirect(f'/manage/{category}')
        else:
            messages.success(request,'Data Deletion Unsuccessfull')
            return HttpResponseRedirect(f'/manage/{category}')
    else:
        return HttpResponseRedirect('/signin')

CHP/templates/base.html
<!DOCTYPE html>
{% load cloudinary %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tabler-icons.min.css' %}">
    <title>ICGH</title>
</head>
<body class="desktopOrPhone">
    {% include 'partials/nav.html' %}
    <script>
        document.querySelector('a[id="appTitle"]').innerHTML="{% block navTitle %}{% endblock navTitle %}"
    </script>
    {% block body %}{% endblock body %}
    <script src="{% static 'js/materialize.min.js' %}"></script>
</body>
<footer style="position: fixed!important;" class="bottom-0 desktopOrPhone w-full z-50">
{% block footer %}{% endblock footer %}
</footer>
</html>

CHP/templates/breifPage.html
{% extends 'base.html' %}
{% block navTitle %}{{allData.0.category.name}}{% endblock navTitle %}
{% block body %}
    <section class="mx-4 my-4">
        {% for data in allData %}
        {% if data.is_shown %}
        <a href="/detailpage/{{data.category.name}}/{{data.id}}" class="no-underline text-black">
            <div class="border-2 border-green-400 rounded-xl p-2 my-2">
                <div class="flex justify-between my-2">
                    <div class="flex">
                        <div class="rounded-full indigo lighten-1 h-14 w-14 flex justify-center">
                            <img  src="{{data.category.icon.url}}" width="25px" height="25px">
                        </div>
                        <div class="mx-2">
                            <span class="text-xl font-semibold">{{data.name}}</span>
                            <p class="font-semibold text-gray-400">{{data.landmark}}</p>
                        </div>
                    </div>
                    <button class="hover:bg-transparent focus:outline-none focus:bg-transparent flex justify-center p-2">
                        <i class="ti ti-2x ti-phone"></i>
                    </button>
                </div>
                <hr class="border border-gray-500 w-10/12 mx-auto">
                <div class="flex justify-between my-2">
                    <div class="mx-2">
                        <span class="text-xl font-semibold">{{data.city}}</span>
                    </div>
                    <div>
                        <p class="font-semibold text-white p-1 rounded-full {% if data.is_verified %}bg-green-400{% else %}bg-red-400{% endif %}">
                            {% if data.is_verified %}
                                Verified
                            {% else %}
                                Not Verified
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </section>
{% endblock body %}

CHP/templates/detailPage.html
{% extends 'base.html' %}
{% block navTitle %}{{data.category.name}}{% endblock navTitle %}
{% block body %}
<div class="grid grid-cols-3 gap-4 text-center">
    <p class="col-span-2 py-4 mx-4 text-3xl text-left">{{data.name}}<br><span class="text-base">{{data.landmark}}</span></p>
    {% if data.is_verified %}
    <div class="py-6 mx-4">
        <p class="bg-green-300 p-1 rounded-full font-semibold">Verified</p>
    </div>
    {% else %}
    <div class="py-6 mx-4">
        <p class="bg-red-300 p-1 rounded-full font-semibold">Not Verified</p>
    </div>
    {% endif %}
</div>
<section>
<div class="flex flex-row mx-2">
    {% if data.website %}
    <a target="_blank" href="{{data.website}}" class="btn-floating waves-effect waves-light blue darken-1 ml-2 my-2" style="text-transform:none!important;">
        <i class="ti ti-2x ti-world"></i>
    </a>
    {% endif %}
    {% if data.mapUrl %}
    <a target="_blank" href="{{data.mapUrl}}" class="btn-floating waves-effect waves-light blue darken-1 ml-2 my-2" style="text-transform:none!important;">
        <i class="ti ti-2x ti-map-2"></i>
    </a>
    {% endif %}
    {% if data.email %}
    <a target="_blank" href="mailto:{{data.email}}" class="btn-floating waves-effect waves-light blue darken-1 ml-2 my-2" style="text-transform:none!important;">
        <i class="ti ti-2x ti-mail"></i>
    </a>
    {% endif %}
</div>
<div class="m-2">
    {% if data.phone1 %}
        <div class="border-2 border-green-400 rounded-xl p-2 my-2 w-full">
            <a href="tel:{{data.phone1}}" class="flex flex-row justify-between">
            <span class="text-black mx-4 ti-lg font-semibold">{{data.phone1}}</span>
            <i class="ti ti-2x ti-phone mx-4"></i>
            </a>
        </div>
    {% endif %}
    {% if data.phone2 %}
        <div class="border-2 border-green-400 rounded-xl p-2 my-2 w-full">
            <a href="tel:{{data.phone2}}" class="flex flex-row justify-between">
            <span class="text-black mx-4 ti-lg font-semibold">{{data.phone2}}</span>
            <i class="ti ti-2x ti-phone mx-4"></i>
            </a>
        </div>
    {% endif %}
    {% if data.phone3 %}
        <div class="border-2 border-green-400 rounded-xl p-2 my-2 w-full">
            <a href="tel:{{data.phone3}}" class="flex flex-row justify-between">
            <span class="text-black mx-4 ti-lg font-semibold">{{data.phone3}}</span>
            <i class="ti ti-2x ti-phone mx-4"></i>
            </a>
        </div>
    {% endif %}
</div>
<p class="m-4">
    <span class="font-semibold">Address :</span>
    {{data.address}}, {{data.landmark}},
    <br>{{data.city}}, {{data.get_state_display}}, {{data.pincode}}
</p>
</section>
<hr>
<section id="dynamic_fields">
    {% if data.field1 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field1}} :</span>
        {{data.field1}}
    </p>
    {% endif %}
    {% if data.field2 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field2}} :</span>
        {{data.field2}}
    </p>
    {% endif %}
    {% if data.field3 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field3}} :</span>
        {{data.field3}}
    </p>
    {% endif %}
    {% if data.field4 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field4}} :</span>
        {{data.field4}}
    </p>
    {% endif %}
    {% if data.field5 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field5}} :</span>
        {{data.field5}}
    </p>
    {% endif %}
    {% if data.field6 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field6}} :</span>
        {{data.field6}}
    </p>
    {% endif %}
    {% if data.field7 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field7}} :</span>
        {{data.field7}}
    </p>
    {% endif %}
    {% if data.field8 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field8}} :</span>
        {{data.field8}}
    </p>
    {% endif %}
    {% if data.field9 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field9}} :</span>
        {{data.field9}}
    </p>
    {% endif %}
    {% if data.field10 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field10}} :</span>
        {{data.field10}}
    </p>
    {% endif %}
    {% if data.field11 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field11}} :</span>
        {{data.field11}}
    </p>
    {% endif %}
    {% if data.field12 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field12}} :</span>
        {{data.field12}}
    </p>
    {% endif %}
    {% if data.field13 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field13}} :</span>
        {{data.field13}}
    </p>
    {% endif %}
    {% if data.field14 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field14}} :</span>
        {{data.field14}}
    </p>
    {% endif %}
    {% if data.field15 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field15}} :</span>
        {{data.field15}}
    </p>
    {% endif %}
    {% if data.field16 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field16}} :</span>
        {{data.field16}}
    </p>
    {% endif %}
    {% if data.field17 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field17}} :</span>
        {{data.field17}}
    </p>
    {% endif %}
    {% if data.field18 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field18}} :</span>
        {{data.field18}}
    </p>
    {% endif %}
    {% if data.field19 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field19}} :</span>
        {{data.field19}}
    </p>
    {% endif %}
    {% if data.field20 %}
    <p class="m-4">
        <span class="font-semibold">{{data.category.field20}} :</span>
        {{data.field20}}
    </p>
    {% endif %}
</section>
{% endblock body %}

CHP/templates/home.html
{% extends 'base.html' %}
{% block navTitle %}ICHG{% endblock navTitle %}
{% block body %}
<div class="hero mx-auto desktopOrPhone bg-white w-100 py-4 sticky z-40">
    <img class="rounded-2xl w-4/5 mx-auto object-contain shadow-lg" src="https://images.moneycontrol.com/static-mcnews/2021/04/Modi-770x433.jpg" alt="">
</div> 
<script>
    topHeight = document.querySelector('#mainNav').clientHeight;
    document.querySelector('.hero').setAttribute('style','top:'+topHeight+'px!important');
</script>
{% if messages %}
    {% for message in messages %}
        <small class="orange accent-2 {% if message.tags %}{{message.tags}}{% endif %}">{{message}}</small>
    {% endfor %}
{% endif %}
<div class="grid gap-4 grid-cols-3 mx-4 my-2">
    {% for category in categories %}
    {% if category.is_shown %}
    <a href="/breifpage/{{category.name}}" class="border-2 flex flex-col items-center text-center text-black font-semibold justify-center border-green-400 shadow-lg rounded-lg p-2">
        <img src="{{category.icon.url}}" width="44px" height="44px"></img>
        {{category.name}}
    </a>
    {% endif %}
    {% endfor %}
</div>
{% endblock body %}

{% block footer %}
<div class="flex h-full items-center justify-around teal accent-3 p-2">
    <a href="#" class="no-underline text-center text-black">
        <i class="ti ti-2x ti-home"></i>
        <br>
        <p class="font-semibold">Home</p> 
    </a>
    <a href="#" class="no-underline text-center text-black">
        <i class="ti ti-2x ti-news"></i>
        <br>
        <p class="font-semibold">News</p> 
        </a>
        <a href="#" class="no-underline text-center text-black">
        <i class="ti ti-2x ti-report-medical"></i>
        <br>
        <p class="font-semibold">Medical</p> 
        </a>
        <a href="#" class="no-underline text-center text-black">
        <i class="ti ti-2x ti-ambulance"></i>
        <br>
        <p class="font-semibold">Ambulance</p> 
        </a>
</div>
{% endblock footer %}